spring:
  # redis 配置
  redis:
    redisson:
      config: classpath:redisson/redisson-dev.yml
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://47.101.207.109:3306/fmds_eeka_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: 'eeka'
        password: 'eeka@123'
      # data center ClickHouse数据源
      data-center-click:
        # 数据源开关/默认关闭
        enabled: false
        driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        url: jdbc:clickhouse://114.67.228.142:8123/default
        username: 'default'
        password: '1q2w3e4r5t'
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

fmds:
  algorithm:
    # 算法服务调用路径
    sdk:
      # 本地服务
      # base-url: http://localhost:8001/
      # 测试环境公用算法服务
      base-url: http://127.0.0.1:8090/algorithm-test/

burgeon:
  url: http://127.0.0.1:300/
  appKey: jd@burgeon.com.cn
  appSecret: jd123

logging:
  level:
    com.oibp.fmds.jupiter.trans.process.service: INFO

knife4j:
  enable: true
  setting:
    enableDebug: true
